name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Ana branch üzerinde değişiklikler olduğunda pipeline çalışır

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Backend Image
      run: |
        docker build -t ahsenka/mern-backend ./backend
        docker push ahsenka/mern-backend

    - name: Build and Push Frontend Image
      run: |
        docker build -t ahsenka/mern-frontend ./frontend
        docker push ahsenka/mern-frontend
