<<<<<<< HEAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: mern-backend
        image: mern-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://admin:password@mongodb-service:27017/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
=======
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: mern-backend
        image: mern-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://admin:password@mongodb-service:27017/mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
>>>>>>> 45e4884cea2addfb4804e4d8a0714ea888e77eb8
